title: Cayman theme #网站名
description: Cayman is a clean, responsive theme for GitHub Pages. #网站描述
#show_downloads: true #显示下载按钮
url: "https://some6508.github.io/" # change this to the base hostname & protocol for your site
google_analytics:
theme: jekyll-theme-cayman  #主题
author: some6508
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
header_page_refs: [] #加载md模版
